name = "hyperrail-worker"
main = "src/worker.ts"
compatibility_date = "2025-09-27"

[observability]
enabled = true

[vars]
LIFI_INTEGRATOR = "HyperRail"
HYPEREVM_RPC = "https://rpc.hyperliquid.xyz/evm"
GIFT_CONTRACT = "0x32e22a4EE21e6D923aa7FbfBDd488F7E3D1E398a"

[[d1_databases]]
binding = "DB"
database_name = "hyper-rail-db"
database_id = "536740c9-3ce8-4d24-8b35-7539f07e03e1"
