name = "hyperrail-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
LIFI_INTEGRATOR = "HyperRail"

[[d1_databases]]
binding = "DB"
database_name = "hyper-rail-db"
database_id = "536740c9-3ce8-4d24-8b35-7539f07e03e1"
